### PR TITLE
Add solution for 951

### PR DESCRIPTION
**Pull request by havanagrawal**
Problem URL: [Flip Equivalent Binary Trees](https://leetcode.com/problems/flip-equivalent-binary-trees/)

### CODE REVIEW

**Comment by fishercoder1534** [comment]
Minor nites, otherwise LGTM!

**Comment by havanagrawal** [comment]
Anything I need to change?

**Comment by fishercoder1534** [comment]
Yes, I've left two minor comments, you cannot see them?
image

**Comment by fishercoder1534** [comment]
That's fine, I'll just merge it and fix the build.

**Comment by havanagrawal** [comment]
Yeah I couldn't see them because the comments were `pending`, you needed to push them out, it happens when you choose "Start a review" instead of "add a single comment"

**Comment by fishercoder1534** [comment]
Very interesting, thanks for the note!

**Pull request merged**
