### PR TITLE
Added _966.java

### PR DESCRIPTION
**Pull request by varunu28**
- [X] Added code with description
 - [X] Added test case
 - [X] Updated README

### CODE REVIEW

**Comment by varunu28** [comment]
@fishercoder1534 Can you please review it?

**Comment by fishercoder1534** [comment]
I did review, looks like my two minor comments are unaddressed yet? @varunu28

**Comment by fishercoder1534** [comment]
Please change
```for (int i=0; i<queries.length; i++) {```
to
```for (int i = 0; i < queries.length; i++) {```
Otherwise, build will fail.
Thanks!

**Comment by fishercoder1534** [comment]
Dang... somehow build still failed: https://travis-ci.org/fishercoder1534/Leetcode/builds/474888119?utm_medium=notification&utm_source=email

**Comment by fishercoder1534** [comment]
Fixed it.

**Comment by fishercoder1534** [comment]
Happy coding! :)

**Pull request merged**
