### PR TITLE
feat: Add javascript Solution2 for 1

### PR DESCRIPTION
**Pull request by yaodehaung**

### CODE REVIEW

**Comment by fishercoder1534** [comment]
https://travis-ci.org/github/fishercoder1534/Leetcode/pull_requests

**Comment by yaodehaung** [comment]
I'm fixing  XD

**Comment by fishercoder1534** [comment]
Please keep the original method var name and wrap Solution* around it. Thanks.

**Comment by yaodehaung** [comment]
example:   var twoSum = {
   
  Solution1: function (){},
  Solution2: function(){} 

}

right?

**Comment by fishercoder1534** [comment]
Please follow conventions similar to this: https://github.com/fishercoder1534/Leetcode/blob/master/src/main/java/com/fishercoder/solutions/_3.java, thanks.

**Comment by fishercoder1534** [comment]
Solution 2 cannot pass this test case:
```
[3,2,4]
6
```
on LeetCode.

Please make sure your solutions are AC'ed on LeetCode. Thanks!

**Comment by yaodehaung** [comment]
@fishercoder1534 thx

**Pull request merged**
