### PR TITLE
added js solution to _3

### PR DESCRIPTION
**Pull request by sambabib**
I solved question 3 in javascript. Hopefully, it helps more javascript-centric devs. Also hope to do a lot more of these but here's my first submission. Thank you.

### CODE REVIEW

**Comment by sambabib** [comment]
I have also added a backtracking javascript solution to question 17. Hopefully, this can help expand the javascript solution base.

**Comment by sambabib** [comment]
> LGTM, can you add links to these two solutions on the README.md as well: https://github.com/fishercoder1534/Leetcode/tree/master/paginated_contents/algorithms/1st_thousand

I just added links to the README.md. At the moment, they point to my fork as the links do not currently exist on this repo. I can update them after the PR has been merged.

**Comment by sambabib** [comment]
You can also let me know your preferred way of doing this. Thank you.

**Comment by fishercoder1534** [comment]
Add them to point the the master branch please, it'll existing once this PR is merged in, thanks!

**Comment by sambabib** [comment]
> Add them to point the the master branch please, it'll existing once this PR is merged in, thanks!

It's all done now. I have just updated the links to point to the master branch.

**Comment by sambabib** [comment]
Quick reminder, the javascript links have been updated as requested.

**Review by fishercoder1534 — APPROVED** [review]

**Pull request merged**
