### PR TITLE
Add solutions for 1020, 1023, 1025, 1029

### PR DESCRIPTION
**Pull request by havanagrawal**
Added solutions for 

1. [1020. Number of Enclaves](https://leetcode.com/problems/number-of-enclaves/)
1. [1023. Camelcase Matching
](https://leetcode.com/problems/camelcase-matching/)
1. [1025. Divisor Game](https://leetcode.com/problems/divisor-game/)
1. [1029. Two City Scheduling](https://leetcode.com/problems/two-city-scheduling/)

Love your repo, would love to contribute to it regularly!

### CODE REVIEW

**Comment by fishercoder1534** [comment]
Thanks a lot for your contribution! 
Could you please separate the 4 problems/solutions into each of its respective commits? i.e. one commit per solution.

Thanks a lot!

**Comment by havanagrawal** [comment]
Yes there are exactly four commits, one for each solution

**Comment by fishercoder1534** [comment]
I mean to open one PR for each commit, instead of having all four commits in one PR, just for easy tracking purpose.
Also, the commit for 1023 doesn't contain the README.md change which resides in the commit of 1025.

A better practice would be to have one commit, in one PR, with one complete solution+test+README.md change, thanks!

**Comment by havanagrawal** [comment]
Ah okay, on it :)

**Pull request closed without merging**
