### PR TITLE
Update _177.sql

### PR DESCRIPTION
**Pull request by CodeToGoodLife**

### CODE REVIEW

**Comment by fishercoder1534** [comment]
Any reasoning for why this change?
I don't see significant performance improvement by this.
Thanks.

**Comment by 10097zhou** [comment]
added GROUP BY Salary.
so new codes can pass by more test cases in leetcode

**Comment by fishercoder1534** [comment]
Which new test cases?
I see the original solution is still AC'ed in Leetcode. :)

**Comment by 10097zhou** [comment]
The status of submitted solution shouldn't be changed after new test cases are added

**Pull request closed without merging**
